apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-k8s-pod
  labels:
    name: spring-boot-k8s-pod
spec:
  containers:
    - image: 'spring-boot-k8s:0.0.1-SNAPSHOT'
      name: spring-boot-k8s
      ports:
        - containerPort: 8080
      env:
        - name: MY_ENV
          value: Kubernetes
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
        successThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 2
        failureThreshold: 3
        successThreshold: 1
